export default {
  myBeats: {},
  beats: {},
  beeAddress: 'http://localhost:1633',
  beatTopic: 'opensocialnetwork.eth/beats',
  biosTopic: 'opensocialnetwork.eth/beater',
  myEthAddress: '',
  postageBatchId: '',
  biosInfo: {},
  othersBiosInfo: {},
  loading: false,
  registered: false,
  logged: false,
  waitForSigner: false,
  beeNodeConnected: false,
  registering: false,
}
